.gitignore
website/siteConfig.js

Fixes [AB#1434](https://amido-dev.visualstudio.com/73884c9a-a68f-4f67-b2b5-b588c2eb8492/_workitems/edit/1434)
Ensure we aren't indexing with search engines.
Turn it off. This has been deployed.
See the releases.
Notes for QA

fix: no indexing website

---

docs/Server side cache.md
packages/template-cli/templates/src/ssr/package-lock.json
packages/template-cli/templates/src/ssr/package.json
packages/template-cli/templates/src/ssr/server/index.ts

#866: Serverside caching
NextJS SSR is very expensive CPU operation. So to optimise serving these pages cache is necessary on the server side on top of Infrastructure options. 
On first attempt the server responds for **_X-Cache miss_**
On following attempts the server responds for **_X-Cache success (or) HIT_**

feat: added cache to the app root

---

libs/images/k8s-deploy/Dockerfile
libs/images/k8s-deploy/README.md
packages/template-cli/templates/build/azDevops/azure/azure-pipeline-infrastructure-ssr.yml

fix: updated ci-k8s deploy image with dotnet core

---

package.json

Don't run the script on postinstall.
Set up this as a task in the pipeline to run, then publish the results.
Notes for QA

fix: seperate task to be run in pipeline

---

lerna.json
packages/eslint-config/CHANGELOG.md
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/template-cli/CHANGELOG.md
packages/template-cli/package-lock.json
packages/template-cli/package.json

Ignore the changes to `package.lock` when publishing with lerna.
Failing in the pipeline to publish due to changes.
Lerna config: https://github.com/lerna/lerna/issues/1508
Notes for QA

fix: lerna publishing 

---

packages/template-cli/templates/test/testcafe/README.md
packages/template-cli/templates/test/testcafe/environment-variables.ts
packages/template-cli/templates/test/testcafe/fixtures/yumido.test.axe.cf.ts
packages/template-cli/templates/test/testcafe/package-lock.json
packages/template-cli/templates/test/testcafe/package.json

Implements [AB#1509](https://amido-dev.visualstudio.com/73884c9a-a68f-4f67-b2b5-b588c2eb8492/_workitems/edit/1509)
Use axe for accessibility testing deployed webpages programmatically and in a pipeline for any url.
Using axe-core.
`npm run test:axe` from `./templates/test/testcafe`

test: axe with test cafe

---

packages/template-cli/templates/src/ssr/.browserslistrc

fix: added browsers list to the SSR

---

.vscode/launch.json
libs/images/sonar-scanner/Dockerfile
libs/images/sonar-scanner/README.md
packages/eslint-config/CHANGELOG.md
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/scaffolding-cli/CHANGELOG.md
packages/scaffolding-cli/jest.config.json
packages/scaffolding-cli/package-lock.json
packages/scaffolding-cli/package.json
packages/scaffolding-cli/sonar-project.properties
packages/scaffolding-cli/src/__tests__/domain/config/worker_maps/netcore_aks_tfs.test.ts
packages/scaffolding-cli/src/__tests__/domain/config/worker_maps/ssr_aks_tfs.test.ts
packages/scaffolding-cli/src/__tests__/domain/netcore.bootstrap-config.json
packages/scaffolding-cli/src/__tests__/domain/workers/main_worker.test.ts
packages/scaffolding-cli/src/__tests__/domain/workers/utils.test.ts
packages/scaffolding-cli/src/domain/config/static.config.json
packages/scaffolding-cli/src/domain/config/worker_maps/netcore_aks_tfs.ts
packages/scaffolding-cli/src/domain/workers/main_worker.ts
packages/scaffolding-cli/src/domain/workers/utils.ts
packages/scaffolding-cli/templates/deploy/azure/infra/ssr/main.tf
packages/scaffolding-cli/tsconfig.json

task: cli clean up and .netcore porting

---

docs/publishing.md
package-lock.json

Fix publishing error with lerna.
Can't publish, blocking the pipeline.
Recreate the package-lock file.
See the publishing.md docs.
Notes for QA

fix: package-lock

---

packages/scaffolding-cli/templates/src/csr/src/App.test.tsx
packages/scaffolding-cli/templates/src/csr/src/App.tsx

Implements a part of [AB#1725](https://amido-dev.visualstudio.com/73884c9a-a68f-4f67-b2b5-b588c2eb8492/_workitems/edit/1725)
Update the jest test with CSR. Haven't changed the jest-config.
Kept Facebooks approach. Updated the test.
Checkout the tests and checks.
`npm run test`

task: jest with csr

---

packages/scaffolding-cli/templates/src/csr/README.md
packages/scaffolding-cli/templates/src/ssr/compositions/create/index.tsx
packages/scaffolding-cli/templates/src/ssr/compositions/home/index.tsx

[AB#1927](https://amido-dev.visualstudio.com/73884c9a-a68f-4f67-b2b5-b588c2eb8492/_workitems/edit/1927)
Notes for QA

fix: redundant calls to the search api

---

packages/scaffolding-cli/templates/src/ssr/README.md
packages/scaffolding-cli/templates/src/ssr/package-lock.json
packages/scaffolding-cli/templates/src/ssr/package.json
packages/scaffolding-cli/templates/src/ssr/utils/appInsightsLogger.ts

AB#{1931}-https://amido-dev.visualstudio.com/Amido-Stacks/_sprints/taskboard/Cycle%203%20-%20Front%20End%20-%20Part%202/Amido-Stacks/Cycle%203%20-%20Front%20End%20-%20Part%202/Sprint%205?workitem=1931
Notes for QA

chore: version update

---

CONTRIBUTING.md

Ensure we have a base contribution guide that links to the common one.
So amazing open-source people know it's opensource and are happy to learn how to contribute!
.md link to /stacks repo.
Notes for QA

docs: contribution guide link

---

CODE_OF_CONDUCT.md

Add link to code of conduct in base repo.
Let's support our community who want to support us.
Notes for QA

docs: add code of conduct link

---

packages/scaffolding-cli/README.md

Quick update to the cli docs, we have more than one project types now!
Notes for QA

docs: scaffolding-cli documentation

---

.vscode/launch.json
packages/scaffolding-cli/package.json
packages/scaffolding-cli/src/__tests__/domain/config/file_mapper.test.ts
packages/scaffolding-cli/src/__tests__/domain/config/questions.test.ts
packages/scaffolding-cli/src/__tests__/domain/javaSpring.bootstrap-config.json
packages/scaffolding-cli/src/__tests__/domain/prompt.test.ts
packages/scaffolding-cli/src/__tests__/domain/selectors.test.ts
packages/scaffolding-cli/src/__tests__/domain/workers/integration_testflow.test.ts
packages/scaffolding-cli/src/__tests__/domain/workers/main_worker.test.ts
packages/scaffolding-cli/src/__tests__/domain/workers/main_worker_testflow.test.ts
packages/scaffolding-cli/src/__tests__/domain/workers/utils.test.ts
packages/scaffolding-cli/src/domain/config/questions.ts
packages/scaffolding-cli/src/domain/config/static.config.json
packages/scaffolding-cli/src/domain/config/worker_maps/java_spring_aks_tfs.ts
packages/scaffolding-cli/src/domain/model/prompt_answer.ts
packages/scaffolding-cli/src/domain/model/workflow.ts
packages/scaffolding-cli/src/domain/prompt.ts
packages/scaffolding-cli/src/domain/selectors.ts
packages/scaffolding-cli/src/domain/workers/main_worker.ts
packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipelines-javaspring-k8s.yml

fix for java spring 
Notes for QA

Fix: java spring

---

.vscode/launch.json
packages/scaffolding-cli/src/__tests__/domain/config/worker_maps/shared.test.ts
packages/scaffolding-cli/src/__tests__/domain/csr.bootstrap-config.json
packages/scaffolding-cli/src/__tests__/domain/workers/main_worker.test.ts
packages/scaffolding-cli/src/domain/config/questions.ts
packages/scaffolding-cli/src/domain/config/static.config.json
packages/scaffolding-cli/src/domain/config/worker_maps/csr_aks_tfs.ts
packages/scaffolding-cli/src/domain/config/worker_maps/java_spring_aks_tfs.ts
packages/scaffolding-cli/src/domain/config/worker_maps/shared.ts
packages/scaffolding-cli/src/domain/config/worker_maps/ssr_aks_tfs.ts
packages/scaffolding-cli/src/domain/workers/main_worker.ts
packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipeline-csr-azure.yml
packages/scaffolding-cli/templates/build/jenkins/azure/ssr-gke.Jenkinsfile

Bring CSR up to par with other project types
Notes for QA

fix: csr properly ported in cli flow

---

packages/scaffolding-cli/templates/test/jest-typescript-sonar/README.md

README on base of boilerplate template.
Notes for QA

docs: sonar-scanner example boilerplate

---

packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipeline-netcore-post-deploy-selenium.yml
packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipeline-post-deploy-testcafe.yml
packages/scaffolding-cli/templates/build/azDevops/azure/templates/steps/build-node.yml
packages/scaffolding-cli/templates/src/ssr/components/Search/index.axe.test.tsx
packages/scaffolding-cli/templates/src/ssr/components/Search/index.test.tsx

fix: type error

---

packages/eslint-config/CHANGELOG.md
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/pact-config/CHANGELOG.md
packages/pact-config/package-lock.json
packages/pact-config/package.json
packages/scaffolding-cli/CHANGELOG.md
packages/scaffolding-cli/package-lock.json
packages/scaffolding-cli/package.json
packages/scaffolding-cli/src/domain/config/static.config.json

chore: csr mapping src folder

---

packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipeline-csr-azure.yml
packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipeline-infrastructure-aks.yml
packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipeline-infrastructure-gke.yml
packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipelines-javaspring-k8s.yml
packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipelines-netcore-k8s.yml
packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipelines-ssr-gke.yml
packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipelines-ssr-new-k8s.yml
packages/scaffolding-cli/templates/build/azDevops/azure/templates/steps/build-csr.yml
packages/scaffolding-cli/templates/build/azDevops/azure/templates/steps/build-java.yml
packages/scaffolding-cli/templates/build/azDevops/azure/templates/steps/build-netcore.yml
packages/scaffolding-cli/templates/build/azDevops/azure/templates/steps/build-node.yml
tests/packages/scaffolding-cli/node-projects/test-scaffolding-cli.yml

Adds updating build pipelines to the templates.
All builds were originally just showing `merge-init`, whereas now they'll show as `major.minor.revision-branch` where branch is a branch or merge for PRs.
Notes for QA

feat: Update Build Pipeline for AZD

---

packages/scaffolding-cli/src/domain/config/static.config.json

Scaffolding CLI was returning Azure Terraform scripts for the SSR app.
Notes for QA

fix: corrected GCP app mapping

---

packages/eslint-config/CHANGELOG.md
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/pact-config/CHANGELOG.md
packages/pact-config/package-lock.json
packages/pact-config/package.json
packages/scaffolding-cli/CHANGELOG.md
packages/scaffolding-cli/package-lock.json
packages/scaffolding-cli/package.json
packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipeline-infrastructure-aks.yml
packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipeline-post-deploy-testcafe.yml
packages/scaffolding-cli/templates/deploy/azure/infra/stacks-aks/main.tf
packages/scaffolding-cli/templates/test/testcafe/README.md
packages/scaffolding-cli/templates/test/testcafe/api/menu.ts
packages/scaffolding-cli/templates/test/testcafe/fixtures/get-menu.test.cf.ts

Adds a Production stage for AKS cluster.
This is needed to have a more stable version of the cluster tied to master, so master versions of stacks apps may be deployed there.

feat: Adds a Production Stacks cluster on master

---

packages/scaffolding-cli/package-lock.json

Lodash version change, Dependabot seems to be getting a bit confused.
Security fix.

fix: Lodash security vuln, depbot fails

---

packages/scaffolding-cli/templates/test/testcafe/api/menu.ts
packages/scaffolding-cli/templates/test/testcafe/fixtures/get-menu.test.cf.ts

Delete and seed the database.
Because data, and tests. But seriously, ensuring state before tests are run.
Interacting with the API, not with the Cosmos DB instance itself.
`npm run test:e2e`

tests: ensure that we are deleting and seeding

---

packages/eslint-config/CHANGELOG.md
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/pact-config/CHANGELOG.md
packages/pact-config/package-lock.json
packages/pact-config/package.json
packages/scaffolding-cli/CHANGELOG.md
packages/scaffolding-cli/package-lock.json
packages/scaffolding-cli/package.json
packages/scaffolding-cli/src/__tests__/domain/workers/integration_testflow.test.ts
packages/scaffolding-cli/src/__tests__/domain/workers/main_worker.test.ts
packages/scaffolding-cli/src/__tests__/domain/workers/utils.test.ts
packages/scaffolding-cli/src/domain/config/questions.ts
packages/scaffolding-cli/src/domain/config/static.config.json
packages/scaffolding-cli/src/domain/config/worker_maps/java_spring_aks_tfs.ts
packages/scaffolding-cli/src/domain/config/worker_maps/shared.ts
packages/scaffolding-cli/src/domain/workers/main_worker.ts
packages/scaffolding-cli/src/domain/workers/utils.ts

* Adds Java Azure DevOps on AKS configs
* Changes some CLI defaults
We need to have our first Java release in the CLI

feat: Adds JavaSpring configs, changes some cli

---

packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipeline-infrastructure-aks.yml
packages/scaffolding-cli/templates/deploy/azure/app/kube/main.tf
packages/scaffolding-cli/templates/deploy/azure/infra/stacks-aks/main.tf
packages/scaffolding-cli/templates/deploy/gcp/app/kube/main.tf

Pins app to 1.3.5 and updates prod var in aks infra to the prod prefixed one.

fix: fixes versions to the latest, var update

---

packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipeline-post-deploy-serenity-frontend.yml
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/README.md
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/pom.xml
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/fixtures/GenericPageSteps.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/fixtures/Hooks.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/fixtures/Requests.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/models/Category.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/models/Item.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/models/Menu.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/models/ResponseWrapper.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/pages/BlogPage.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/pages/CreateMenuPage.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/pages/MainPage.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/starter/CucumberTestSuiteUI.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/starter/stepdefinitions/CreateMenuStepDefinitions.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/starter/stepdefinitions/SearchMenuStepDefinitions.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/resources/features/CreateMenu.feature
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/resources/serenity.conf

fix some bugs

---

package-lock.json
packages/eslint-config/CHANGELOG.md
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/pact-config/CHANGELOG.md
packages/pact-config/package-lock.json
packages/pact-config/package.json
packages/scaffolding-cli/CHANGELOG.md
packages/scaffolding-cli/package-lock.json
packages/scaffolding-cli/package.json
packages/scaffolding-cli/src/domain/config/static.config.json

Updated scaffolding-cli to use the latest version of stacks-dotnet (which includes jwt bearer authentication).
https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/2531
To include JWT bearer authentication in the Stacks .NET Core template.
Notes for QA

Updated scaffolding-cli to use the latest version of stacks-dotnet

---

packages/eslint-config/CHANGELOG.md
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/pact-config/CHANGELOG.md
packages/pact-config/package-lock.json
packages/pact-config/package.json
packages/scaffolding-cli/CHANGELOG.md
packages/scaffolding-cli/package-lock.json
packages/scaffolding-cli/package.json
packages/scaffolding-cli/src/index.ts

fix: Fixes the version number checker

---

packages/eslint-config/CHANGELOG.md
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/pact-config/CHANGELOG.md
packages/pact-config/package-lock.json
packages/pact-config/package.json
packages/scaffolding-cli/CHANGELOG.md
packages/scaffolding-cli/package-lock.json
packages/scaffolding-cli/package.json
packages/scaffolding-cli/src/__tests__/domain/config/worker_maps/ssr_aks_tfs.test.ts
packages/scaffolding-cli/src/domain/config/worker_maps/ssr_aks_tfs.ts
packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipelines-ssr-aks.yml

Make the SSR pipeline reusable for multiple deployments.
To deploy an SSR app that consumes the Java API alongside the existing one.
Use a pipeline variables to where relevant (terraform workspace, k8s namespace, etc). Pipeline variables are set against the pipeline in Azure DevOps
Notes for QA

feat: ssr app using java api

---

packages/scaffolding-cli/templates/test/cypress-typescript-coreui/compositions/home/functionalityManifest.test.cy.ts
packages/scaffolding-cli/templates/test/cypress-typescript-coreui/compositions/home/performance.test.cy.ts
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Selenium/Selenium/Factory/RemoteWebDriverFactory.cs
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Selenium/xxAMIDOxx.xxSTACKSxx.E2E.Selenium.csproj

Fix Cypress Tests

---

packages/scaffolding-cli/src/__tests__/domain/config/questions.test.ts
packages/scaffolding-cli/src/__tests__/domain/config/static.config.test.ts
packages/scaffolding-cli/src/__tests__/domain/workers/utils.test.ts
packages/scaffolding-cli/src/domain/config/questions.ts
packages/scaffolding-cli/src/domain/config/static.config.json
packages/scaffolding-cli/src/domain/config/worker_maps/java_spring_aks_tfs.ts
packages/scaffolding-cli/src/domain/model/config.ts
packages/scaffolding-cli/src/domain/model/prompt_answer.ts
packages/scaffolding-cli/src/domain/workers/main_worker.ts
packages/scaffolding-cli/src/domain/workers/utils.ts

Update the CLI to allow selecting a testing framework for the Java API. 
Notes for QA

feat: add karate testing option for java api

---

build/azDevOps/azure/templates/steps/build-install-dependencies-node.yml
packages/eslint-config/CHANGELOG.md
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/pact-config/CHANGELOG.md
packages/pact-config/package-lock.json
packages/pact-config/package.json
packages/scaffolding-cli/CHANGELOG.md
packages/scaffolding-cli/package-lock.json
packages/scaffolding-cli/package.json
packages/scaffolding-cli/src/__tests__/domain/config/questions.test.ts
packages/scaffolding-cli/src/__tests__/domain/config/worker_maps/shared.test.ts
packages/scaffolding-cli/src/__tests__/domain/workers/main_worker.test.ts
packages/scaffolding-cli/src/domain/config/questions.ts
packages/scaffolding-cli/src/domain/config/worker_maps/infra_aks_tfs.ts
packages/scaffolding-cli/src/domain/config/worker_maps/shared.ts
packages/scaffolding-cli/src/domain/workers/main_worker.ts
packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipeline-infrastructure-aks.yml
packages/scaffolding-cli/templates/deploy/azure/infra/stacks-aks/main.tf
packages/scaffolding-cli/templates/deploy/azure/infra/stacks-aks/vars.tf

- Reorder CLI questions inline with the GitHub documentation
- Update azure infra replacements
Notes for QA

chore: cli consistency with documentation

---

packages/eslint-config/CHANGELOG.md
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/pact-config/CHANGELOG.md
packages/pact-config/package-lock.json
packages/pact-config/package.json
packages/scaffolding-cli/CHANGELOG.md
packages/scaffolding-cli/package-lock.json
packages/scaffolding-cli/package.json
packages/scaffolding-cli/src/__tests__/domain/config/static.config.test.ts
packages/scaffolding-cli/src/domain/config/questions.ts
packages/scaffolding-cli/src/domain/config/static.config.json
packages/scaffolding-cli/src/domain/model/prompt_answer.ts
packages/scaffolding-cli/src/domain/model/workflow.ts
packages/scaffolding-cli/src/domain/workers/main_worker.ts
packages/scaffolding-cli/src/domain/workers/utils.ts

Add a workload for Java API with CQRS.
Notes for QA

feat: java api with cqrs option

---

packages/eslint-config/CHANGELOG.md
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/pact-config/CHANGELOG.md
packages/pact-config/package-lock.json
packages/pact-config/package.json
packages/scaffolding-cli/CHANGELOG.md
packages/scaffolding-cli/package-lock.json
packages/scaffolding-cli/package.json
packages/scaffolding-cli/src/domain/workers/main_worker.ts

fix: netcore filename replace on removed files

---

packages/eslint-config/CHANGELOG.md
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/pact-config/CHANGELOG.md
packages/pact-config/package-lock.json
packages/pact-config/package.json
packages/scaffolding-cli/CHANGELOG.md
packages/scaffolding-cli/package-lock.json
packages/scaffolding-cli/package.json
packages/scaffolding-cli/src/__tests__/domain/config/worker_maps/netcore_aks_tfs.test.ts
packages/scaffolding-cli/src/__tests__/domain/workers/main_worker.test.ts
packages/scaffolding-cli/src/domain/config/worker_maps/netcore_aks_tfs.ts

chore: netcore replacements

---

packages/eslint-config/CHANGELOG.md
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/pact-config/CHANGELOG.md
packages/pact-config/package-lock.json
packages/pact-config/package.json
packages/scaffolding-cli/CHANGELOG.md
packages/scaffolding-cli/package-lock.json
packages/scaffolding-cli/package.json
packages/scaffolding-cli/src/domain/config/questions.ts

chore: question prompts update

---

packages/eslint-config/CHANGELOG.md
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/pact-config/CHANGELOG.md
packages/pact-config/package-lock.json
packages/pact-config/package.json
packages/scaffolding-cli/CHANGELOG.md
packages/scaffolding-cli/package-lock.json
packages/scaffolding-cli/package.json
packages/scaffolding-cli/src/domain/config/static.config.json

Update scaffolding CLI to use latest Java commits
Get the latest changes
Notes for QA

chore: java commit updates

---

packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/README.md
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/pom.xml
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/fixtures/AuthorizationRequestActions.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/fixtures/OAuthConfigurations.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/fixtures/Requests.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/models/AuthorizationRequest.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/pages/MainPage.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/starter/Hooks.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/starter/stepdefinitions/CreateMenuStepDefinitions.java
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/resources/serenity.conf

Turn on Auth0 for Serenity tests

---

packages/scaffolding-cli/src/__tests__/domain/config/worker_maps/ssr_aks_tfs.test.ts
packages/scaffolding-cli/src/domain/config/static.config.json
packages/scaffolding-cli/src/domain/config/worker_maps/ssr_aks_tfs.ts
packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipelines-ssr-aks.yml
packages/scaffolding-cli/templates/src/ssr/server/index.ts
packages/scaffolding-cli/templates/src/ssr/server/middlewares/helmet/index.ts

- Enable cypress tests
- Fix failing test by setting x-xss-protection header (https://github.com/helmetjs/helmet/issues/273)
- Make TestCafe test run post-deploy
Cypress tests were failing but were not being run as part of the pipeline so we were unaware. TestCafe were running after the CI stage and would fail for new deployments with one Azure DevOps agent
Notes for QA

fix: ssr functional tests

---

packages/eslint-config/CHANGELOG.md
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/pact-config/CHANGELOG.md
packages/pact-config/package-lock.json
packages/pact-config/package.json
packages/scaffolding-cli/CHANGELOG.md
packages/scaffolding-cli/package-lock.json
packages/scaffolding-cli/package.json
packages/scaffolding-cli/src/__tests__/domain/config/worker_maps/netcore_aks_tfs.test.ts
packages/scaffolding-cli/src/__tests__/domain/config/worker_maps/ssr_aks_tfs.test.ts
packages/scaffolding-cli/src/domain/config/questions.ts
packages/scaffolding-cli/src/domain/config/static.config.json
packages/scaffolding-cli/src/domain/config/worker_maps/csr_aks_tfs.ts
packages/scaffolding-cli/src/domain/config/worker_maps/infra_aks_tfs.ts
packages/scaffolding-cli/src/domain/config/worker_maps/java_spring_aks_tfs.ts
packages/scaffolding-cli/src/domain/config/worker_maps/netcore_aks_tfs.ts
packages/scaffolding-cli/src/domain/config/worker_maps/ssr_aks_tfs.ts
packages/scaffolding-cli/src/domain/workers/main_worker.ts
packages/scaffolding-cli/templates/shared/README.md

Update project types to match documentation headings. Update shared README to point to documentation.
Notes for QA

chore: cli updates to match documentation

---

packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/pom.xml

Fix the Serenity dependencies

---

packages/scaffolding-cli/templates/build/azDevops/azure/azure-pipeline-post-deploy-serenity-frontend.yml
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/pom.xml
packages/scaffolding-cli/templates/test/xxAMIDOxx.xxSTACKSxx.E2E.Serenity/src/test/java/com/xxAMIDOxx/xxSTACKSxx/ui/fixtures/Requests.java

changed pom dependencies

---

packages/eslint-config/CHANGELOG.md
packages/eslint-config/package-lock.json
packages/eslint-config/package.json
packages/pact-config/CHANGELOG.md
packages/pact-config/package-lock.json
packages/pact-config/package.json
packages/scaffolding-cli/CHANGELOG.md
packages/scaffolding-cli/package-lock.json
packages/scaffolding-cli/package.json
packages/scaffolding-cli/src/domain/config/static.config.json

fix: bumps dotnet version and package version

---

libs/images/dind-alpine-aws/Dockerfile

Updating base image and glibc versions
Fixing vulnerabilities
Notes for QA

fix(sec): updating the alpine aws docker image

---

libs/images/tf-k8s-aws-alpine/Dockerfile
libs/images/tf-k8s-aws-alpine/README.md

Updated the Terraform version to 1.0.2.
We need to upgrade to Terraform 1.0.2
Notes for QA

Update Terraform to use latest version
